# docker stack deploy -c docker-compose.yml myweb
version: '3.7'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /var/www:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - webnet

  php:
    image: php:fpm-alpine
    volumes:
      - /var/www:/var/www/html
    networks:
      - webnet

networks:
  webnet:
