version: '3.7'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /var/www/html:/var/www/html
      - /var/www/conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - training

  php:
    image: php:fpm-alpine
    volumes:
      - /var/www/html:/var/www/html
    networks:
      - training

  nginx2:
    image: nginx:latest
    ports:
      - "8888:80"
    networks:
      - training


networks:
  training:
    driver: overlay
    attachable: true
    internal: true
    ipam:
      config:
        - subnet: 172.66.66.0/24
    driver_opts:
      encrypted: "true"
