version: '3.7'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /var/www/html:/var/www/html
      - /var/www/conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - training
    # deploy:
    #   mode: global

  php:
    image: php:fpm-alpine
    volumes:
      - /var/www/html:/var/www/html
    networks:
      - training

  alpine_container:
    image: alpine:latest
    command: tail -f /dev/null  # Keeps the container running
    networks:
      - training

networks:
  training:
    driver: overlay
    attachable: true
    internal: true
    # ipam:
    #   config:
    #     - subnet: 172.66.66.0/24
    driver_opts:
      encrypted: "true"
