version: '3.7'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /var/www/html:/var/www/html
      - /var/www/conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - training

  php:
    image: php:fpm-alpine
    volumes:
      - /var/www/html:/var/www/html
    networks:
      - training

networks:
  training:
    driver: overlay
    attachable: false
    internal: true
