version: '3.1'

services:

  mysql:
    image: mariadb:10.5-bionic

    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysafepass
    volumes:
    - ./docker/db-data:/var/lib/mysql 

  myjavaapp:
    build: ./javaapp
    image: myjavaapp:0.1
    # environment:
    #   - APP_ENV=dev
    ports:
      - 8337:8080
